---
- name: Upload configuration files as configlets to CloudVision
  hosts: cvp1
  gather_facts: false
  vars_files:
    - ../vars/CVP_model.yml

  tasks:
    - name: Build CVP_CONFIGLETS dictionary on the fly
      ansible.builtin.set_fact:
        CVP_CONFIGLETS: "{{ CVP_CONFIGLETS | default({}) | combine({'OSPF_' ~ item: lookup('file', path ~ '/configs/' ~ item ~ '.cfg')}) }}"
      loop: "{{ groups['fabric'] }}"

    - name: Upload configlets to CloudVision
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"
